### ISSUE TITLE
Issue with position of "More Unreads" notice

### ISSUE THREAD

**Issue by jodizzle** [jakebathman/Rocket-Chat-Inverted#7]
Rocket.Chat displays a "More Unreads" banner on the channel sidebar when there are unread messages in an out-of-focus channel.  This banner is placed at the top or bottom of the channel sidebar, depending on whether the user needs to scroll up or down, respectively, to see the channel where the unread messages are.  Using the Rocket-Chat-Inverted style causes the bottom-placement of the banner to be odd, positioning it where the top of the footer image would be if it hadn't been removed, rather than at the visible bottom of the channel sidebar.

(This is sort of hard to describe, so I'll see if I can grab a clean screenshot at some point.)

Rocket.Chat v0.53.0.

**Comment by jakebathman** [comment]
Just figured out how to trigger this. You have to disable "Unread Rooms Mode" in preferences to have the bar show up at the bottom of the sidebar.

### Fix

```css
.side-nav .unread-rooms.bottom-unread-rooms {
    bottom: 0px;
}
```

**Comment by jodizzle** [comment]
Thanks!  The recent update seems to have fixed my issues.
